import pathlib

content = (
    "from __future__ import annotations\n"
    "from dataclasses import dataclass\n"
    "from datetime import date\n"
    "from typing import Optional\n"
    "import numpy as np\n"
    "from scipy.stats import norm\n"
    "\n"
    "\n"
    "def _bs_price(S, K, T, r, sigma, q, is_call: bool) -> float:\n"
    "    if T <= 0 or sigma <= 0:\n"
    "        return max(0.0, (S - K) if is_call else (K - S))\n"
    "    d1 = (np.log(S / K) + (r - q + 0.5 * sigma**2) * T) / (sigma * np.sqrt(T))\n"
    "    d2 = d1 - sigma * np.sqrt(T)\n"
    "    if is_call:\n"
    "        return float(S * np.exp(-q * T) * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2))\n"
    "    return float(K * np.exp(-r * T) * norm.cdf(-d2) - S * np.exp(-q * T) * norm.cdf(-d1))\n"
    "\n"
    "\n"
    "def _bs_greeks(S, K, T, r, sigma, q, is_call: bool) -> dict:\n"
    "    if T <= 0 or sigma <= 0:\n"
    "        return {'delta': 0.0, 'gamma': 0.0, 'theta': 0.0, 'vega': 0.0, 'rho': 0.0}\n"
    "    sqT = np.sqrt(T)\n"
    "    d1 = (np.log(S / K) + (r - q + 0.5 * sigma**2) * T) / (sigma * sqT)\n"
    "    d2 = d1 - sigma * sqT\n"
    "    nd1 = norm.pdf(d1)\n"
    "    delta = (np.exp(-q * T) * norm.cdf(d1) if is_call else -np.exp(-q * T) * norm.cdf(-d1))\n"
    "    gamma = np.exp(-q * T) * nd1 / (S * sigma * sqT)\n"
    "    vega  = S * np.exp(-q * T) * nd1 * sqT / 100\n"
    "    if is_call:\n"
    "        theta = (-S * np.exp(-q * T) * nd1 * sigma / (2 * sqT) - r * K * np.exp(-r * T) * norm.cdf(d2) + q * S * np.exp(-q * T) * norm.cdf(d1))\n"
    "        rho = K * T * np.exp(-r * T) * norm.cdf(d2) / 100\n"
    "    else:\n"
    "        theta = (-S * np.exp(-q * T) * nd1 * sigma / (2 * sqT) + r * K * np.exp(-r * T) * norm.cdf(-d2) - q * S * np.exp(-q * T) * norm.cdf(-d1))\n"
    "        rho = -K * T * np.exp(-r * T) * norm.cdf(-d2) / 100\n"
    "    return {'delta': float(delta), 'gamma': float(gamma), 'theta': float(theta / 365), 'vega': float(vega), 'rho': float(rho)}\n"
    "\n"
    "\n"
    "def _binomial_price(S, K, T, r, sigma, q, is_call: bool, american: bool = False, n: int = 200) -> float:\n"
    "    dt = T / n\n"
    "    u  = np.exp(sigma * np.sqrt(dt))\n"
    "    d  = 1 / u\n"
    "    disc = np.exp(-r * dt)\n"
    "    p  = np.clip((np.exp((r - q) * dt) - d) / (u - d), 0, 1)\n"
    "    j  = np.arange(n + 1)\n"
    "    ST = S * u**(n - j) * d**j\n"
    "    pf = np.maximum(ST - K, 0) if is_call else np.maximum(K - ST, 0)\n"
    "    for step in range(n - 1, -1, -1):\n"
    "        pf = disc * (p * pf[:-1] + (1 - p) * pf[1:])\n"
    "        if american:\n"
    "            j2     = np.arange(len(pf))\n"
    "            ST_now = S * u**(step - j2) * d**j2\n"
    "            intr   = np.maximum(ST_now - K, 0) if is_call else np.maximum(K - ST_now, 0)\n"
    "            pf     = np.maximum(pf, intr)\n"
    "    return float(pf[0])\n"
    "\n"
    "\n"
    "def _mc_price(S, K, T, r, sigma, q, is_call: bool, n_paths: int = 10_000, seed: int = 42):\n"
    "    rng = np.random.default_rng(seed)\n"
    "    Z   = rng.standard_normal(n_paths)\n"
    "    ST  = S * np.exp((r - q - 0.5 * sigma**2) * T + sigma * np.sqrt(T) * Z)\n"
    "    pf  = np.maximum(ST - K, 0) if is_call else np.maximum(K - ST, 0)\n"
    "    disc_pf = np.exp(-r * T) * pf\n"
    "    return float(disc_pf.mean()), float(disc_pf.std(ddof=1) / np.sqrt(n_paths))\n"
    "\n"
    "\n"
    "@dataclass\n"
    "class ValuationResult:\n"
    "    call_price: float\n"
    "    put_price:  float\n"
    "    bs_call:    float = 0.0\n"
    "    bs_put:     float = 0.0\n"
    "    bin_call:   float = 0.0\n"
    "    bin_put:    float = 0.0\n"
    "    mc_call:    float = 0.0\n"
    "    mc_put:     float = 0.0\n"
    "    mc_se:      float = 0.0\n"
    "    delta_call: float = 0.0\n"
    "    gamma:      float = 0.0\n"
    "    theta:      float = 0.0\n"
    "    vega:       float = 0.0\n"
    "    rho:        float = 0.0\n"
    "    company_name:   str    = ''\n"
    "    stock_price:    float  = 0.0\n"
    "    strike_price:   float  = 0.0\n"
    "    risk_free_rate: float  = 0.0\n"
    "    volatility:     float  = 0.0\n"
    "    T:              float  = 0.0\n"
    "    dividend_yield: float  = 0.0\n"
    "    industry:       str    = ''\n"
    "    currency:       str    = 'JPY'\n"
    "    valuation_date: object = None\n"
    "\n"
    "\n"
    "@dataclass\n"
    "class VolatilityMeta:\n"
    "    vol_method: str = 'historical'\n"
    "    vol_period: str = '1y'\n"
    "    vol_source: str = ''\n"
    "    vol_data:   str = ''\n"
    "\n"
    "\n"
    "class ValuationService:\n"
    "    WEIGHTS = {'bs': 0.50, 'binomial': 0.30, 'mc': 0.20}\n"
    "\n"
    "    def calculate(self, company_name, stock_price, strike_price, risk_free_rate, volatility, T, dividend_yield=0.0, industry='general', valuation_date=None, currency='JPY', american=False, n_steps=200, n_paths=10_000):\n"
    "        S, K, r, s, q = stock_price, strike_price, risk_free_rate, volatility, dividend_yield\n"
    "        bs_c  = _bs_price(S, K, T, r, s, q, True)\n"
    "        bs_p  = _bs_price(S, K, T, r, s, q, False)\n"
    "        gr    = _bs_greeks(S, K, T, r, s, q, True)\n"
    "        bin_c = _binomial_price(S, K, T, r, s, q, True,  american, n_steps)\n"
    "        bin_p = _binomial_price(S, K, T, r, s, q, False, american, n_steps)\n"
    "        mc_c, mc_se = _mc_price(S, K, T, r, s, q, True,  n_paths)\n"
    "        mc_p, _     = _mc_price(S, K, T, r, s, q, False, n_paths)\n"
    "        w = self.WEIGHTS\n"
    "        call = w['bs']*bs_c + w['binomial']*bin_c + w['mc']*mc_c\n"
    "        put  = w['bs']*bs_p + w['binomial']*bin_p + w['mc']*mc_p\n"
    "        return ValuationResult(\n"
    "            call_price=call, put_price=put,\n"
    "            bs_call=bs_c, bs_put=bs_p,\n"
    "            bin_call=bin_c, bin_put=bin_p,\n"
    "            mc_call=mc_c, mc_put=mc_p, mc_se=mc_se,\n"
    "            delta_call=gr['delta'], gamma=gr['gamma'],\n"
    "            theta=gr['theta'], vega=gr['vega'], rho=gr['rho'],\n"
    "            company_name=company_name,\n"
    "            stock_price=S, strike_price=K,\n"
    "            risk_free_rate=r, volatility=s, T=T,\n"
    "            dividend_yield=q, industry=industry,\n"
    "            currency=currency,\n"
    "            valuation_date=valuation_date or date.today(),\n"
    "        )\n"
    "\n"
    "    def save(self, result, option_type='call', vol_meta=None):\n"
    "        try:\n"
    "            from src.data.database import get_db_manager\n"
    "            from src.data.models import ValuationCase, ValuationParameter, ValuationResult as ORMResult\n"
    "            meta = vol_meta or VolatilityMeta()\n"
    "            db = get_db_manager()\n"
    "            with db.get_session() as session:\n"
    "                case = ValuationCase(\n"
    "                    case_name=f'{result.company_name} - {result.valuation_date}',\n"
    "                    company_name=result.company_name,\n"
    "                    is_deleted=0,\n"
    "                    notes=f'industry: {result.industry}, currency: {result.currency}',\n"
    "                )\n"
    "                session.add(case)\n"
    "                session.flush()\n"
    "                param = ValuationParameter(\n"
    "                    case_id=case.id,\n"
    "                    stock_price=result.stock_price,\n"
    "                    strike_price=result.strike_price,\n"
    "                    time_to_expiry=result.T,\n"
    "                    risk_free_rate=result.risk_free_rate,\n"
    "                    volatility=result.volatility,\n"
    "                    dividend_yield=result.dividend_yield,\n"
    "                    option_type=option_type,\n"
    "                    vol_method=meta.vol_method,\n"
    "                    vol_period=meta.vol_period,\n"
    "                    vol_source=meta.vol_source,\n"
    "                    vol_data=meta.vol_data,\n"
    "                )\n"
    "                session.add(param)\n"
    "                records = [\n"
    "                    ('weighted_call', result.call_price,  result.delta_call, result.gamma, result.theta, result.vega, result.rho),\n"
    "                    ('weighted_put',  result.put_price,   None, result.gamma, None, result.vega, None),\n"
    "                    ('bs_call',       result.bs_call,     result.delta_call, result.gamma, result.theta, result.vega, result.rho),\n"
    "                    ('bs_put',        result.bs_put,      None, result.gamma, None, result.vega, None),\n"
    "                    ('binomial_call', result.bin_call,    None, None, None, None, None),\n"
    "                    ('binomial_put',  result.bin_put,     None, None, None, None, None),\n"
    "                    ('mc_call',       result.mc_call,     None, None, None, None, None),\n"
    "                    ('mc_put',        result.mc_put,      None, None, None, None, None),\n"
    "                ]\n"
    "                for model_type, option_value, delta, gamma, theta, vega, rho in records:\n"
    "                    session.add(ORMResult(\n"
    "                        case_id=case.id,\n"
    "                        model_type=model_type,\n"
    "                        option_value=option_value,\n"
    "                        delta=delta, gamma=gamma,\n"
    "                        theta=theta, vega=vega, rho=rho,\n"
    "                    ))\n"
    "                return case.id\n"
    "        except Exception:\n"
    "            import traceback\n"
    "            traceback.print_exc()\n"
    "            return None\n"
)

import pathlib
pathlib.Path('src/services/valuation_service.py').write_text(content, encoding='utf-8')
print('DONE')

c = pathlib.Path('src/services/valuation_service.py').read_text(encoding='utf-8')
checks = [
    ('VolatilityMeta class', 'class VolatilityMeta'),
    ('vol_meta in save',     'vol_meta=None'),
    ('vol_method saved',     'vol_method=meta.vol_method'),
    ('vol_period saved',     'vol_period=meta.vol_period'),
]
for label, kw in checks:
    print(('OK' if kw in c else 'NG') + ' ' + label)
