import sys
sys.stdout.reconfigure(encoding='utf-8')

lines = open('src/ui/pages/case_detail.py', encoding='utf-8').readlines()

new_block = []
new_block.append('        st.markdown("**' + '正規分布値の計算' + '**")\n')
new_block.append('        if opt == "call":\n')
new_block.append('            st.code(\n')
new_block.append('                f"N(d1) = {norm.cdf(d1):.6f}\\nN(d2) = {norm.cdf(d2):.6f}",\n')
new_block.append('                language="text"\n')
new_block.append('            )\n')
new_block.append('            price_bs = S * math.exp(-q*T) * norm.cdf(d1) - K * math.exp(-r*T) * norm.cdf(d2)\n')
new_block.append('            st.latex(r"C = S e^{-qT} N(d_1) - K e^{-rT} N(d_2)")\n')
new_block.append('            st.code(\n')
new_block.append('                f"C = {S}*e^(-{q}*{T})*{norm.cdf(d1):.6f} - {K}*e^(-{r}*{T})*{norm.cdf(d2):.6f}\\n"\n')
new_block.append('                f"  = {S*math.exp(-q*T)*norm.cdf(d1):.4f} - {K*math.exp(-r*T)*norm.cdf(d2):.4f}\\n"\n')
new_block.append('                f"  = {price_bs:.4f}",\n')
new_block.append('                language="text"\n')
new_block.append('            )\n')
new_block.append('        else:\n')
new_block.append('            st.code(\n')
new_block.append('                f"N(-d1) = {norm.cdf(-d1):.6f}\\nN(-d2) = {norm.cdf(-d2):.6f}",\n')
new_block.append('                language="text"\n')
new_block.append('            )\n')
new_block.append('            price_bs = K * math.exp(-r*T) * norm.cdf(-d2) - S * math.exp(-q*T) * norm.cdf(-d1)\n')
new_block.append('            st.latex(r"P = K e^{-rT} N(-d_2) - S e^{-qT} N(-d_1)")\n')
new_block.append('            st.code(\n')
new_block.append('                f"P = {K}*e^(-{r}*{T})*{norm.cdf(-d2):.6f} - {S}*e^(-{q}*{T})*{norm.cdf(-d1):.6f}\\n"\n')
new_block.append('                f"  = {K*math.exp(-r*T)*norm.cdf(-d2):.4f} - {S*math.exp(-q*T)*norm.cdf(-d1):.4f}\\n"\n')
new_block.append('                f"  = {price_bs:.4f}",\n')
new_block.append('                language="text"\n')
new_block.append('            )\n')

new_lines = lines[:123] + new_block + lines[149:]
open('src/ui/pages/case_detail.py', 'w', encoding='utf-8').writelines(new_lines)
print('Done! Total lines:', len(new_lines))
