python -c "
import pathlib, ast

p = pathlib.Path('src/ui/pages/case_detail.py')
p.parent.mkdir(parents=True, exist_ok=True)

# ASCII onlyで書き出す
content = (
    'from __future__ import annotations\n'
    '\n'
    'import traceback\n'
    'import streamlit as st\n'
    'import numpy as np\n'
    'import matplotlib\n'
    'matplotlib.use(\"Agg\")\n'
    'import matplotlib.pyplot as plt\n'
    '\n'
    'from src.services.valuation_service import ValuationService, ValuationParams\n'
    '\n'
    '\n'
    'def _get_service():\n'
    '    return ValuationService()\n'
    '\n'
    '\n'
    'def _fetch_case(case_id):\n'
    '    return _get_service().get_case(case_id)\n'
    '\n'
    '\n'
    'def _build_params(p, case_name=\"\"):\n'
    '    return ValuationParams(\n'
    '        case_name      = case_name or p.get(\"case_name\", \"\"),\n'
    '        stock_price    = float(p.get(\"stock_price\",    100)),\n'
    '        strike_price   = float(p.get(\"strike_price\",   100)),\n'
    '        risk_free_rate = float(p.get(\"risk_free_rate\", 0.02)),\n'
    '        volatility     = float(p.get(\"volatility\",     0.30)),\n'
    '        time_to_expiry = float(p.get(\"time_to_expiry\", 1.0)),\n'
    '        option_type    = p.get(\"option_type\", \"call\"),\n'
    '        dividend_yield = float(p.get(\"dividend_yield\", 0.0)),\n'
    '        binomial_steps = int(p.get(\"binomial_steps\",   100)),\n'
    '        mc_simulations = int(p.get(\"mc_simulations\",   10000)),\n'
    '    )\n'
    '\n'
    '\n'
    'def _plot_mc_histogram(payoffs, price):\n'
    '    import numpy as _np\n'
    '    arr = _np.array(payoffs, dtype=float)\n'
    '    fig, ax = plt.subplots(figsize=(7, 3))\n'
    '    ax.hist(arr, bins=60, color=\"#4C8BF5\", edgecolor=\"white\", alpha=0.85)\n'
    '    ax.axvline(price, color=\"red\", linewidth=1.8, linestyle=\"--\",\n'
    '               label=\"MC Price: \" + f\"{price:.2f}\")\n'
    '    ax.set_xlabel(\"Payoff\")\n'
    '    ax.set_ylabel(\"Frequency\")\n'
    '    ax.set_title(\"Monte Carlo Payoff Distribution\")\n'
    '    ax.legend()\n'
    '    plt.tight_layout()\n'
    '    st.pyplot(fig)\n'
    '    plt.close(fig)\n'
    '\n'
    '\n'
    'def _fmt(v):\n'
    '    if isinstance(v, float): return f\"{v:.6f}\"\n'
    '    if isinstance(v, int):   return f\"{v:,}\"\n'
    '    if isinstance(v, list):\n'
    '        preview = [f\"{x:.4f}\" if isinstance(x, float) else str(x) for x in v[:4]]\n'
    '        tail = \" ...\" if len(v) > 4 else \"\"\n'
    '        return \"[\" + \", \".join(preview) + tail + \"]\"\n'
    '    return str(v)\n'
    '\n'
    '\n'
    'def _show_scalars(d, skip=(\"ST_hist\", \"payoff_hist\")):\n'
    '    items = [(k, v) for k, v in d.items()\n'
    '             if k not in skip and not isinstance(v, list)]\n'
    '    if not items:\n'
    '        st.info(\"No data.\")\n'
    '        return\n'
    '    cols = st.columns(3)\n'
    '    for idx, (k, v) in enumerate(items):\n'
    '        cols[idx % 3].metric(k, _fmt(v))\n'
    '\n'
    '\n'
    'def _show_list_items(d, skip=(\"ST_hist\", \"payoff_hist\")):\n'
    '    for k, v in d.items():\n'
    '        if k not in skip and isinstance(v, list):\n'
    '            with st.expander(f\"- {k} ({len(v)} items)\", expanded=False):\n'
    '                st.write(v)\n'
    '\n'
    '\n'
    'def _init_edit_state(case, case_id):\n'
    '    if st.session_state.get(\"_edit_case_id\") != case_id:\n'
    '        st.session_state[\"_edit_case_id\"]     = case_id\n'
    '        st.session_state[\"edit_case_name\"]    = case.get(\"case_name\", \"\")\n'
    '        st.session_state[\"edit_stock_price\"]  = float(case.get(\"stock_price\",    100))\n'
    '        st.session_state[\"edit_strike\"]       = float(case.get(\"strike_price\",   100))\n'
    '        st.session_state[\"edit_rate\"]         = float(case.get(\"risk_free_rate\", 0.02))\n'
    '        st.session_state[\"edit_div\"]          = float(case.get(\"dividend_yield\", 0.0))\n'
    '        st.session_state[\"edit_vol\"]          = float(case.get(\"volatility\",     0.30))\n'
    '        st.session_state[\"edit_tte\"]          = float(case.get(\"time_to_expiry\", 1.0))\n'
    '        st.session_state[\"edit_opt_type\"]     = case.get(\"option_type\", \"call\")\n'
    '        st.session_state[\"edit_bin_steps\"]    = int(case.get(\"binomial_steps\",   100))\n'
    '        st.session_state[\"edit_mc_sims\"]      = int(case.get(\"mc_simulations\",   10000))\n'
    '        st.session_state[\"edit_result\"]       = None\n'
    '        st.session_state[\"edit_result_dirty\"] = True\n'
    '\n'
    '\n'
    'def _read_edit_state():\n'
    '    return dict(\n'
    '        case_name      = st.session_state.get(\"edit_case_name\",   \"\"),\n'
    '        stock_price    = st.session_state.get(\"edit_stock_price\", 100.0),\n'
    '        strike_price   = st.session_state.get(\"edit_strike\",      100.0),\n'
    '        risk_free_rate = st.session_state.get(\"edit_rate\",        0.02),\n'
    '        volatility     = st.session_state.get(\"edit_vol\",         0.30),\n'
    '        time_to_expiry = st.session_state.get(\"edit_tte\",         1.0),\n'
    '        option_type    = st.session_state.get(\"edit_opt_type\",    \"call\"),\n'
    '        dividend_yield = st.session_state.get(\"edit_div\",         0.0),\n'
    '        binomial_steps = st.session_state.get(\"edit_bin_steps\",   100),\n'
    '        mc_simulations = st.session_state.get(\"edit_mc_sims\",     10000),\n'
    '    )\n'
    '\n'
    '\n'
    'def _show_comparable_vol_selector(case_id):\n'
    '    svc = _get_service()\n'
    '    try:\n'
    '        tickers = svc.get_comparable_tickers(case_id)\n'
    '    except Exception:\n'
    '        tickers = []\n'
    '    if not tickers:\n'
    '        return\n'
    '    st.markdown(\"---\")\n'
    '    st.markdown(\"**Comparable Company Volatility**\")\n'
    '    rows = []\n'
    '    for t in tickers:\n'
    '        vol = t.get(\"volatility\") or t.get(\"vol\")\n'
    '        if vol is not None:\n'
    '            rows.append({\n'
    '                \"ticker\":     t.get(\"ticker\", \"\"),\n'
    '                \"company\":    t.get(\"company_label\") or t.get(\"ticker\", \"\"),\n'
    '                \"volatility\": float(vol),\n'
    '            })\n'
    '    if not rows:\n'
    '        st.caption(\"No comparable companies with volatility data.\")\n'
    '        return\n'
    '    cols = st.columns([2, 2, 2, 1])\n'
    '    cols[0].markdown(\"**Ticker**\")\n'
    '    cols[1].markdown(\"**Company**\")\n'
    '    cols[2].markdown(\"**Volatility**\")\n'
    '    cols[3].markdown(\"**Apply**\")\n'
    '    for row in rows:\n'
    '        c0, c1, c2, c3 = st.columns([2, 2, 2, 1])\n'
    '        c0.write(row[\"ticker\"])\n'
    '        c1.write(row[\"company\"])\n'
    '        c2.write(f\"{row[\'volatility\']:.1%}\")\n'
    '        btn_key = \"apply_vol_\" + row[\"ticker\"] + \"_\" + str(case_id)\n'
    '        if c3.button(\"Apply\", key=btn_key):\n'
    '            st.session_state[\"edit_vol\"] = row[\"volatility\"]\n'
    '            st.rerun()\n'
    '\n'
    '\n'
    'def show():\n'
    '    case_id = st.session_state.get(\"detail_case_id\")\n'
    '    if not case_id:\n'
    '        st.warning(\"No case selected.\")\n'
    '        if st.button(\"Back to Home\"):\n'
    '            st.session_state[\"current_page\"] = \"home\"\n'
    '            st.rerun()\n'
    '        return\n'
    '    case = _fetch_case(case_id)\n'
    '    if not case:\n'
    '        st.error(f\"Case ID={case_id} not found.\")\n'
    '        return\n'
    '    _init_edit_state(case, case_id)\n'
    '    st.title(\"Case Detail: \" + case.get(\"case_name\", \"\"))\n'
    '    tab_edit, tab_result, tab_mc = st.tabs(\n'
    '        [\"Edit Parameters\", \"Valuation Results\", \"MC Histogram\"]\n'
    '    )\n'
    '    with tab_edit:\n'
    '        st.subheader(\"Edit Parameters\")\n'
    '        col1, col2 = st.columns(2)\n'
    '        with col1:\n'
    '            st.session_state[\"edit_case_name\"] = st.text_input(\n'
    '                \"Case Name\", value=st.session_state[\"edit_case_name\"],\n'
    '                key=\"_w_case_name\")\n'
    '            st.session_state[\"edit_stock_price\"] = st.number_input(\n'
    '                \"Stock Price (S)\", value=st.session_state[\"edit_stock_price\"],\n'
    '                step=1.0, key=\"_w_stock_price\")\n'
    '            st.session_state[\"edit_strike\"] = st.number_input(\n'
    '                \"Strike Price (K)\", value=st.session_state[\"edit_strike\"],\n'
    '                step=1.0, key=\"_w_strike\")\n'
    '            st.session_state[\"edit_rate\"] = st.number_input(\n'
    '                \"Risk-Free Rate\", value=st.session_state[\"edit_rate\"],\n'
    '                step=0.001, format=\"%.3f\", key=\"_w_rate\")\n'
    '            st.session_state[\"edit_div\"] = st.number_input(\n'
    '                \"Dividend Yield\", value=st.session_state[\"edit_div\"],\n'
    '                step=0.001, format=\"%.3f\", key=\"_w_div\")\n'
    '        with col2:\n'
    '            new_vol = st.number_input(\n'
    '                \"Volatility\", value=st.session_state[\"edit_vol\"],\n'
    '                step=0.01, format=\"%.3f\", key=\"_w_vol\")\n'
    '            st.session_state[\"edit_vol\"] = new_vol\n'
    '            st.session_state[\"edit_tte\"] = st.number_input(\n'
    '                \"Time to Expiry (T)\", value=st.session_state[\"edit_tte\"],\n'
    '                step=0.1, format=\"%.2f\", key=\"_w_tte\")\n'
    '            opt_options = [\"call\", \"put\"]\n'
    '            opt_idx = 0 if st.session_state[\"edit_opt_type\"] == \"call\" else 1\n'
    '            selected = st.selectbox(\n'
    '                \"Option Type\", opt_options, index=opt_idx, key=\"_w_opt_type\")\n'
    '            st.session_state[\"edit_opt_type\"] = selected\n'
    '            st.session_state[\"edit_bin_steps\"] = int(st.number_input(\n'
    '                \"Binomial Steps\", value=st.session_state[\"edit_bin_steps\"],\n'
    '                step=10, min_value=10, key=\"_w_bin_steps\"))\n'
    '            st.session_state[\"edit_mc_sims\"] = int(st.number_input(\n'
    '                \"MC Simulations\", value=st.session_state[\"edit_mc_sims\"],\n'
    '                step=1000, min_value=1000, key=\"_w_mc_sims\"))\n'
    '        _show_comparable_vol_selector(case_id)\n'
    '        st.divider()\n'
    '        btn_col1, btn_col2, btn_col3, btn_col4 = st.columns(4)\n'
    '        with btn_col1:\n'
    '            calc_btn = st.button(\"Recalculate\", type=\"primary\",\n'
    '                                  use_container_width=True)\n'
    '        with btn_col2:\n'
    '            save_btn = st.button(\"Save\", use_container_width=True)\n'
    '        with btn_col3:\n'
    '            new_name_input = st.text_input(\n'
    '                \"Save As Name\", value=\"\", key=\"_w_new_name\",\n'
    '                label_visibility=\"collapsed\", placeholder=\"New case name\")\n'
    '            saveas_btn = st.button(\"Save As\", use_container_width=True)\n'
    '        with btn_col4:\n'
    '            del_btn = st.button(\"Delete\", type=\"secondary\",\n'
    '                                 use_container_width=True)\n'
    '        edited = _read_edit_state()\n'
    '        svc    = _get_service()\n'
    '        if calc_btn:\n'
    '            with st.spinner(\"Calculating...\"):\n'
    '                try:\n'
    '                    params = _build_params(edited)\n'
    '                    result = svc.calculate(params)\n'
    '                    st.session_state[\"edit_result\"]       = result\n'
    '                    st.session_state[\"edit_result_dirty\"] = False\n'
    '                    st.success(\"Recalculation complete.\")\n'
    '                except Exception as e:\n'
    '                    st.error(\"Calculation error: \" + str(e))\n'
    '                    st.code(traceback.format_exc())\n'
    '        if save_btn:\n'
    '            try:\n'
    '                params = _build_params(edited)\n'
    '                svc.update_case(case_id, params)\n'
    '                st.success(\"Saved.\")\n'
    '                st.session_state[\"edit_result_dirty\"] = True\n'
    '            except Exception as e:\n'
    '                st.error(\"Save error: \" + str(e))\n'
    '                st.code(traceback.format_exc())\n'
    '        if saveas_btn:\n'
    '            name = new_name_input.strip() or (edited[\"case_name\"] + \"_copy\")\n'
    '            try:\n'
    '                params = _build_params(edited, name)\n'
    '                result = svc.calculate(params)\n'
    '                svc.save(p=params, r=result)\n'
    '                st.success(\"Saved as: \" + name)\n'
    '            except Exception as e:\n'
    '                st.error(\"Save As error: \" + str(e))\n'
    '                st.code(traceback.format_exc())\n'
    '        if del_btn:\n'
    '            try:\n'
    '                svc.delete_case(case_id)\n'
    '                st.success(\"Deleted.\")\n'
    '                st.session_state[\"current_page\"]   = \"home\"\n'
    '                st.session_state[\"detail_case_id\"] = None\n'
    '                st.rerun()\n'
    '            except Exception as e:\n'
    '                st.error(\"Delete error: \" + str(e))\n'
    '                st.code(traceback.format_exc())\n'
    '        result = st.session_state.get(\"edit_result\")\n'
    '        if result:\n'
    '            st.divider()\n'
    '            st.subheader(\"Latest Result Preview\")\n'
    '            if st.session_state.get(\"edit_result_dirty\"):\n'
    '                st.warning(\"Parameters changed. Please recalculate.\")\n'
    '            m1, m2, m3, m4 = st.columns(4)\n'
    '            m1.metric(\"BS Price\",       f\"{result.bs_price:,.2f}\")\n'
    '            m2.metric(\"Binomial Price\", f\"{result.binomial_price:,.2f}\")\n'
    '            m3.metric(\"MC Price\",       f\"{result.mc_price:,.2f}\")\n'
    '            m4.metric(\"Weighted Price\", f\"{result.weighted_price:,.2f}\")\n'
    '        else:\n'
    '            st.info(\"Press Recalculate to see results.\")\n'
    '    with tab_result:\n'
    '        result = st.session_state.get(\"edit_result\")\n'
    '        if result is None:\n'
    '            st.info(\"Please run Recalculate in the Edit tab.\")\n'
    '        else:\n'
    '            if st.session_state.get(\"edit_result_dirty\"):\n'
    '                st.warning(\"Parameters changed. Please recalculate.\")\n'
    '            st.subheader(\"Price Summary\")\n'
    '            m1, m2, m3, m4 = st.columns(4)\n'
    '            m1.metric(\"BS Price\",       f\"{result.bs_price:,.2f}\")\n'
    '            m2.metric(\"Binomial Price\", f\"{result.binomial_price:,.2f}\")\n'
    '            m3.metric(\"MC Price\",       f\"{result.mc_price:,.2f}\")\n'
    '            m4.metric(\"Weighted Price\", f\"{result.weighted_price:,.2f}\")\n'
    '            st.divider()\n'
    '            st.subheader(\"Greeks (BS)\")\n'
    '            g1, g2, g3, g4, g5 = st.columns(5)\n'
    '            g1.metric(\"Delta\", f\"{result.delta:.4f}\")\n'
    '            g2.metric(\"Gamma\", f\"{result.gamma:.6f}\")\n'
    '            g3.metric(\"Theta\", f\"{result.theta:.4f}\")\n'
    '            g4.metric(\"Vega\",  f\"{result.vega:.4f}\")\n'
    '            g5.metric(\"Rho\",   f\"{result.rho:.4f}\")\n'
    '            st.divider()\n'
    '            with st.expander(\"Black-Scholes Detail\", expanded=False):\n'
    '                _show_scalars(result.bs_detail or {})\n'
    '            with st.expander(\"Binomial Model Detail\", expanded=False):\n'
    '                d_bin = result.bin_detail or {}\n'
    '                _show_scalars(d_bin) if d_bin else st.info(\"No data.\")\n'
    '                _show_list_items(d_bin)\n'
    '            with st.expander(\"Monte Carlo Detail\", expanded=False):\n'
    '                d_mc = result.mc_detail or {}\n'
    '                if d_mc:\n'
    '                    _show_scalars(d_mc, skip=(\"ST_hist\", \"payoff_hist\"))\n'
    '                    payoffs = d_mc.get(\"payoff_hist\", [])\n'
    '                    if payoffs:\n'
    '                        st.markdown(\"**Payoff Distribution**\")\n'
    '                        _plot_mc_histogram(payoffs, result.mc_price)\n'
    '                else:\n'
    '                    st.info(\"No data.\")\n'
    '    with tab_mc:\n'
    '        st.subheader(\"Monte Carlo Simulation (Full Run)\")\n'
    '        if st.button(\"Run Simulation\", type=\"primary\"):\n'
    '            with st.spinner(\"Calculating...\"):\n'
    '                try:\n'
    '                    edited2 = _read_edit_state()\n'
    '                    params  = _build_params(edited2)\n'
    '                    res     = _get_service().calculate(params)\n'
    '                    mc      = res.mc_detail or {}\n'
    '                    payoffs = mc.get(\"payoff_hist\", [])\n'
    '                    if payoffs:\n'
    '                        _plot_mc_histogram(payoffs, res.mc_price)\n'
    '                    else:\n'
    '                        st.warning(\"No payoff data available.\")\n'
    '                    r1c1, r1c2, r1c3 = st.columns(3)\n'
    '                    r1c1.metric(\"MC Price\",    f\"{res.mc_price:,.2f}\")\n'
    '                    r1c2.metric(\"95% CI Low\",  f\"{mc.get(\'ci95_lower\', 0):,.2f}\")\n'
    '                    r1c3.metric(\"95% CI High\", f\"{mc.get(\'ci95_upper\', 0):,.2f}\")\n'
    '                    r2c1, r2c2, r2c3 = st.columns(3)\n'
    '                    r2c1.metric(\"ITM Ratio\",     f\"{mc.get(\'itm_ratio\', 0):.1%}\")\n'
    '                    r2c2.metric(\"Std Error\",     f\"{mc.get(\'std_error\', 0):.4f}\")\n'
    '                    r2c3.metric(\"N Simulations\", f\"{mc.get(\'n_simulations\', 0):,}\")\n'
    '                except Exception as e:\n'
    '                    st.error(\"MC Error: \" + str(e))\n'
    '                    st.code(traceback.format_exc())\n'
    '    st.divider()\n'
    '    if st.button(\"Back to Home\", key=\"btn_home_bottom\"):\n'
    '        st.session_state[\"current_page\"]   = \"home\"\n'
    '        st.session_state[\"detail_case_id\"] = None\n'
    '        st.rerun()\n'
    '\n'
    '\n'
    'def render():\n'
    '    show()\n'
)

p.write_bytes(content.encode('utf-8'))
data = p.read_bytes()
print('0x81:', data.count(b'\x81'))
print('size:', len(data))
ast.parse(content)
print('Syntax OK')
"
